### ISSUE TITLE
Fix bug in document type recognition

### ISSUE THREAD

**Issue by Joeran** [Mr-DLib/mdl-server#50]
select \* from documents where id_original="gesis-smarth-0000000972"

this document (and several others) have an "unknown" document type. probably because there are two different types in the XML

```
 <field name="doctype_lit_add_str_mv">Aufsatz</field>
 <field name="doctype_lit_str">Zeitschriftenaufsatz</field>
```

@MillahMau how can we solve this? do we have a matching for "Aufsatz" und "Zeitschriftenaufsatz"? Actually, I would say that both should be matched to document.type="essay".

**Comment by SophieSiebert** [comment]
1. doctype_lit_add_str_mv is currently not parsed
2. Zeitschriftenaufsatz is currently mapped to journal_article
   (together with Journal Article, Journal Article (aja), Zeitschriftenaufsatz; Graue Literatur, Articles, Special Issue: Articles)
3. Aufsatz doesn't even have a handling (because it didn't appeared, because of 1.)
4. enum essay don't exist, - only review essay

**Comment by Joeran** [comment]
> doctype_lit_add_str_mv is currently not parsed
> Zeitschriftenaufsatz is currently mapped to journal_article 

ok, but shouldn't the document type in the DB then be "journal_article" instead of "unkown"?
