### ISSUE TITLE
Create Beta System (beta url in website; beta db; if possible beta solr)

### ISSUE THREAD

**Issue by SophieSiebert** [Mr-DLib/mdl-server#53]

**Comment by Joeran** [comment]
when you create the beta system, keep in mind that our server has currently not too much space on its hard-disk. if you believe the hard disk is too small, we need to find a solution. maybe it would be best to rent the same server again (it's not a good idea anyway to have the develop and and production system on the same server).

and: please don't call the system "Beta" but better "Dev" (or "Develop") because in the long run, we will have a develop;beta; and productive system and what we want right now is a develop and productive system.

**Comment by Joeran** [comment]
i will move this ticket to the next milestone, this way we can ensure to finish milestone 0.2 today. i want to have a drink today :-) :-) :-)
